version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node-browsers
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            npm install
            gem install percy-cli

      - run:
          name: run tests
          command: |
            npm run build
            percy snapshot about
            percy snapshot blog
            percy snapshot contact
            percy snapshot faq
            percy snapshot pagenotfound
            percy snapshot plansandpricing
            percy snapshot products
            percy snapshot service
            percy snapshot testimonials
            percy snapshot index.html
